# stacks/redis.yml

- name: Crear directorios para vol√∫menes
  file:
    path: "{{ item }}"
    state: directory
    mode: '0755'
  loop:
    - "{{ ROOT_DATA_DIR }}/redis"

- name: Ejecutar Docker Compose
  community.docker.docker_compose_v2:
    project_src: ../docker/redis
    state: present
  environment:
    ROOT_DATA_DIR: "{{ ROOT_DATA_DIR }}"
    TIMEZONE: "{{ TIMEZONE }}"
    REDIS_DOMAIN: "{{ REDIS_DOMAIN }}"
  register: result

- name: Mostrar resultado
  debug:
    msg: "{{ result }}"
